local setup = require("LYRD.shared.setup")

setup.load({
	layers = {
		"LYRD.layers.general",
		"LYRD.layers.icons",
		"LYRD.layers.commands",
		"LYRD.layers.mappings",
		"LYRD.layers.lyrd-commands",
		"LYRD.layers.lyrd-ui",
		"LYRD.layers.lyrd-keyboard",
		"LYRD.layers.buffers",
		"LYRD.layers.themes",
		"LYRD.layers.clipboard",
		"LYRD.layers.tmux",
		"LYRD.layers.motions",
		"LYRD.layers.file_templates",
		"LYRD.layers.dev",
		"LYRD.layers.environment",
		"LYRD.layers.text",
		"LYRD.layers.test",
		"LYRD.layers.git",
		"LYRD.layers.lsp",
		"LYRD.layers.foldings",
		"LYRD.layers.rest",
		"LYRD.layers.treesitter",
		"LYRD.layers.filetree",
		"LYRD.layers.telescope",
		"LYRD.layers.snippets",
		"LYRD.layers.completion",
		"LYRD.layers.debug",
		"LYRD.layers.docker",
		"LYRD.layers.kubernetes",
		"LYRD.layers.tasks", -- Must be after debug and database
		"LYRD.layers.repl",
		"LYRD.layers.ai-dev",
		"LYRD.layers.lang.bash",
		"LYRD.layers.lang.cmake",
		"LYRD.layers.lang.csv",
		"LYRD.layers.lang.grpc",
		"LYRD.layers.lang.dotnet",
		"LYRD.layers.lang.go",
		"LYRD.layers.lang.java",
		"LYRD.layers.lang.cpp",
		"LYRD.layers.lang.kotlin",
		"LYRD.layers.lang.groovy",
		"LYRD.layers.lang.latex",
		"LYRD.layers.lang.lua",
		"LYRD.layers.lang.markdown",
		"LYRD.layers.lang.pascal",
		"LYRD.layers.lang.python",
		"LYRD.layers.lang.rust",
		"LYRD.layers.lang.ruby",
		"LYRD.layers.lang.php",
		"LYRD.layers.lang.sql",
		"LYRD.layers.lang.data-formats",
		"LYRD.layers.lang.web-frontend",
		"LYRD.layers.lang.web-standard",
		"LYRD.layers.lang.ci_cd",
		"LYRD.layers.lang.nginx",
		"LYRD.layers.static-website",
		"LYRD.layers.grammar",
		"LYRD.layers.extras",
		"LYRD.layers.media",
		"LYRD.layers.neovide", -- Neovide settings
		"LYRD.layers.vscode", -- VsCode settings
	},
})
