local setup = require("LYRD.setup")
local mappings = require("LYRD.layers.mappings")
local menu_header = mappings.menu_header
local submode_header = mappings.submode_header
local commands = require("LYRD.layers.commands")
local c = commands.command_shortcut
local cmd = require("LYRD.layers.lyrd-commands").cmd
local icons = require("LYRD.layers.icons")

local L = {
	name = "LYRD Keyboard",
	ai_keys = {
		-- Accept the current completion.
		accept = "<C-l>",
		-- Accept the next word.
		accept_word = "<C-Right>",
		-- Accept the next line.
		accept_line = "<C-PageDown>",
		-- Clear the virtual text.
		clear = "<C-Left>",
		-- Cycle to the next completion.
		next = "<C-Down>",
		-- Cycle to the previous completion.
		prev = "<C-Up>",
	},
}

function L.plugins(s)
	setup.plugin(s, {
		{
			-- Navigates using brackets (buffers, diagnostics, etc.)
			"echasnovski/mini.bracketed",
			opts = {},
		},
		{
		    -- Text operators g=: evaluate, gx: exchange, multiply: gm, sort: gs, replace with register: gr
			"echasnovski/mini.operators",
			opts = {},
		},
		{
		    -- new a/i objects around/inside next/last
			"echasnovski/mini.ai",
			opts = {},
		},
	})
end

function L.keybindings(s)
	mappings.keys(s, {
		{ "n", "<C-j>", cmd.LYRDPaneNavigateDown },
		{ "n", "<C-k>", cmd.LYRDPaneNavigateUp },
		{ "n", "<C-h>", cmd.LYRDPaneNavigateLeft },
		{ "n", "<C-l>", cmd.LYRDPaneNavigateRight },
		{ "n", "q", "<nop>" },
		{ "n", "s", "<nop>" },
		{ "n", "<F2>", cmd.LYRDViewFileTree },
		{ "n", "<F3>", cmd.LYRDViewFileExplorer },
		{ "n", "<F4>", cmd.LYRDTestSummary },
		{ "n", "<S-F5>", cmd.LYRDDebugStart },
		{ "n", "<F5>", cmd.LYRDDebugContinue },
		{ "n", "<F6>", cmd.LYRDViewCodeOutline },
		{ "n", "<F9>", cmd.LYRDDebugBreakpoint },
		{ "n", "<F10>", cmd.LYRDDebugStepOver },
		{ "n", "<F11>", cmd.LYRDDebugStepInto },
		{ "n", "<F12>", cmd.LYRDDebugStepOut },
		{ "n", "<C-s>", cmd.LYRDBufferSave },
		{ "i", "<C-s>", cmd.LYRDBufferSave:exit_mode_and_run() },
		{ "n", "<C-p>", cmd.LYRDSearchFiles },
		{ "n", "<C-t>", cmd.LYRDSearchLiveGrep },
		{ "n", "<C-f>", cmd.LYRDResumeLastSearch },
		{ "n", "K", cmd.LYRDLSPHoverInfo },
		{ "n", "<C-S-k>", cmd.LYRDLSPSignatureHelp },
		{ "n", "gd", cmd.LYRDLSPFindDefinitions },
		{ "n", "gD", cmd.LYRDLSPFindDeclaration },
		{ "n", "gt", cmd.LYRDLSPFindTypeDefinition },
		{ "n", "gi", cmd.LYRDLSPFindImplementations },
		{ "n", "gr", cmd.LYRDLSPFindReferences },
		{
			"n",
			"gO",
			c([[call append(line('.')-1, '')]]),
			{ desc = "Insert line above cursor" },
		},
		{
			"n",
			"go",
			c([[call append(line('.'), '')]]),
			{ desc = "Insert line below cursor" },
		},
		{ "n", "<M-PageUp>", cmd.LYRDLSPGotoPrevDiagnostic },
		{ "n", "<M-PageDown>", cmd.LYRDLSPGotoNextDiagnostic },
		{ "n", "<M-Enter>", cmd.LYRDLSPFindCodeActions },
		{ "n", "<C-r><C-r>", cmd.LYRDLSPRename },
		{ "n", "<C-r><C-f>", cmd.LYRDCodeRefactor },
		{ "v", "<C-r><C-f>", cmd.LYRDCodeRefactor },
		{ "n", "<M-C-]>", cmd.LYRDBufferNext },
		{ "i", "<M-C-]>", cmd.LYRDBufferNext:exit_mode_and_run() },
		{ "n", "<M-C-[>", cmd.LYRDBufferPrev },
		{ "i", "<M-C-[>", cmd.LYRDBufferPrev:exit_mode_and_run() },
		{ "x", "<Leader>x", cmd.LYRDCodeRunSelection:as_range_command() },
		{ "n", "<S-CR>", cmd.LYRDCodeRunSelection },
	})

	mappings.create_menu("<Leader>", {
		menu_header("h", "Http Requests", {
			{ "a", cmd.LYRDHttpSendAllRequests },
			{ "e", cmd.LYRDHttpEnvironmentFileSelect },
			{ "h", cmd.LYRDHttpSendRequest },
		}, icons.http.default),
		menu_header("i", "Images", {
			{ "p", cmd.LYRDPasteImage },
			{ "i", cmd.LYRDInsertImage },
		}, icons.images.default),
		menu_header("n", "Notebook", {
			menu_header("r", "Run", {
				{ "X", cmd.LYRDReplNotebookRunCell },
				{ "x", cmd.LYRDReplNotebookRunCellAndMove },
				{ "e", cmd.LYRDReplNotebookRunAllCells },
				{ "a", cmd.LYRDReplNotebookRunAllAbove },
				{ "b", cmd.LYRDReplNotebookRunAllBelow },
			}, icons.code.run),
			menu_header("m", "Move", {
				{ "u", cmd.LYRDReplNotebookMoveCellUp },
				{ "d", cmd.LYRDReplNotebookMoveCellDown },
			}, icons.action.move),
			{ "n", cmd.LYRDReplView },
			{ "<BS>", cmd.LYRDReplRestart },
			{ "x", cmd.LYRDReplNotebookRunCellAndMove },
			{ "a", cmd.LYRDReplNotebookAddCellAbove },
			{ "b", cmd.LYRDReplNotebookAddCellBelow },
		}, icons.file.notebook),
		menu_header("s", "Scratches", {
			{ "f", cmd.LYRDScratchSearch },
			{ "n", cmd.LYRDScratchNew },
			{ "s", cmd.LYRDScratchOpen },
		}, icons.file.scratch),
		menu_header("r", "Refactors", {
			{ "f", cmd.LYRDCodeRefactor },
			{ "n", cmd.LYRDLSPRename },
		}, icons.code.refactor),
		menu_header("<Leader>", "Panels", {
			submode_header("r", "Resize", {
				{ "j", cmd.LYRDPaneResizeDown },
				{ "k", cmd.LYRDPaneResizeUp },
				{ "h", cmd.LYRDPaneResizeLeft },
				{ "l", cmd.LYRDPaneResizeRight },
			}, icons.arrow.collapse),
			submode_header("s", "Swap", {
				{ "j", cmd.LYRDPaneSwapDown },
				{ "k", cmd.LYRDPaneSwapUp },
				{ "h", cmd.LYRDPaneSwapLeft },
				{ "l", cmd.LYRDPaneSwapRight },
			}, icons.arrow.swap),
			{ ".", cmd.LYRDViewHomePage },
			{ "D", cmd.LYRDLSPShowWorkspaceDiagnosticLocList },
			{ "c", cmd.LYRDViewRegisters },
			{ "d", cmd.LYRDLSPShowDocumentDiagnosticLocList },
			{ "e", cmd.LYRDViewFileExplorer },
			{ "f", cmd.LYRDViewFileTree },
			{ "g", cmd.LYRDDebugToggleUI },
			{ "h", cmd.LYRDBufferSplitH },
			{ "l", cmd.LYRDViewLocationList },
			{ "o", cmd.LYRDViewCodeOutline },
			{ "p", cmd.LYRDViewTreeSitterPlayground },
			{ "q", cmd.LYRDViewQuickFixList },
			{ "t", cmd.LYRDTestSummary },
			{ "v", cmd.LYRDBufferSplitV },
			{ "y", cmd.LYRDViewYankList },
			{ "x", cmd.LYRDTerminalList },
			{ "X", cmd.LYRDTerminal },
		}, icons.action.split_v),
		{ "<Enter>", cmd.LYRDWindowZoom },
		{ "<Space>", cmd.LYRDClearSearchHighlights },
		{ "a", cmd.LYRDLSPFindCodeActions },
		{ "c", cmd.LYRDBufferClose },
		{ "f", cmd.LYRDBufferFormat },
		{ "j", cmd.LYRDSmartCoder },
		{ "d", cmd.LYRDDiagnosticLinesToggle },
		{ "t", cmd.LYRDApplyNextTheme },
		{ "x", cmd.LYRDCodeRunSelection },
		{ "]", cmd.LYRDBufferNext },
		{ "[", cmd.LYRDBufferPrev },
	})

	mappings.create_menu("<Space>", {
		menu_header("a", "Artificial Intelligence", {
			{ "a", cmd.LYRDAIAssistant },
			{ "r", cmd.LYRDAIRefactor },
			{ "s", cmd.LYRDAISuggestions },
		}, icons.other.ia),
		menu_header("b", "Buffers", {
			{ "e", cmd.LYRDBufferNew },
			{ "n", cmd.LYRDBufferNext },
			{ "p", cmd.LYRDBufferPrev },
			{ "d", cmd.LYRDBufferClose },
			{ "D", cmd.LYRDBufferForceClose },
			{ "f", cmd.LYRDBufferFormat },
			{ "x", cmd.LYRDBufferCloseAll },
			{ "X", cmd.LYRDBufferForceCloseAll },
			{ "h", cmd.LYRDBufferSplitH },
			{ "v", cmd.LYRDBufferSplitV },
			{ "w", cmd.LYRDBufferSetReadOnly },
			{ "Y", cmd.LYRDBufferCopy },
			{ "P", cmd.LYRDBufferPaste },
			{ "/", cmd.LYRDSearchBuffers },
			{ "s", cmd.LYRDBufferSave },
			{ "S", cmd.LYRDBufferSaveAll },
		}, icons.file.default),
		menu_header("c", "Code", {
			menu_header("g", "Code Generation", {
				{ "x", cmd.LYRDCodeGenerate },
				{ "g", cmd.LYRDCodeProduceGetter },
				{ "s", cmd.LYRDCodeProduceSetter },
				{ "m", cmd.LYRDCodeProduceMapping },
			}, icons.code.generate),
			menu_header("n", "Notebook", {
				menu_header("r", "Run", {
					{ "X", cmd.LYRDReplNotebookRunCell },
					{ "x", cmd.LYRDReplNotebookRunCellAndMove },
					{ "e", cmd.LYRDReplNotebookRunAllCells },
					{ "a", cmd.LYRDReplNotebookRunAllAbove },
					{ "b", cmd.LYRDReplNotebookRunAllBelow },
				}, icons.code.run),
				menu_header("m", "Move", {
					{ "u", cmd.LYRDReplNotebookMoveCellUp },
					{ "d", cmd.LYRDReplNotebookMoveCellDown },
				}, icons.action.move),
				{ "n", cmd.LYRDReplView },
				{ "<BS>", cmd.LYRDReplRestart },
				{ "x", cmd.LYRDReplNotebookRunCellAndMove },
				{ "a", cmd.LYRDReplNotebookAddCellAbove },
				{ "b", cmd.LYRDReplNotebookAddCellBelow },
			}, icons.file.notebook),
			{ "A", cmd.LYRDLSPFindRangeCodeActions },
			{ "B", cmd.LYRDCodeBuildAll },
			{ "I", cmd.LYRDCodeImplementInterface },
			{ "S", cmd.LYRDCodeInsertSnippet },
			{ "a", cmd.LYRDLSPFindCodeActions },
			{ "b", cmd.LYRDCodeBuild },
			{ "c", cmd.LYRDCodeGlobalCheck },
			{ "d", cmd.LYRDCodeAddDocumentation },
			{ "e", cmd.LYRDCodeSelectEnvironment },
			{ "f", cmd.LYRDCodeFillStructure },
			{ "i", cmd.LYRDCodeFixImports },
			{ "l", cmd.LYRDDiagnosticLinesToggle },
			{ "m", cmd.LYRDCodeMakeTasks },
			{ "p", cmd.LYRDCodeRestorePackages },
			{ "r", cmd.LYRDCodeRefactor },
			{ "s", cmd.LYRDCodeSecrets },
			{ "t", cmd.LYRDCodeAlternateFile },
			{ "x", cmd.LYRDCodeRun },
		}, icons.other.code),
		menu_header("d", "Debug", {
			{ "y", cmd.LYRDDebugStart },
			{ "k", cmd.LYRDDebugContinue },
			{ "j", cmd.LYRDDebugStepInto },
			{ "l", cmd.LYRDDebugStepOver },
			{ "u", cmd.LYRDDebugStepOut },
			{ "h", cmd.LYRDDebugStop },
			{ "b", cmd.LYRDDebugBreakpoint },
			{ ";", cmd.LYRDDebugToggleUI },
			{ "/", cmd.LYRDDebugToggleRepl },
		}, icons.debug.breakpoint),
		menu_header("f", "Find", {
			{ ".", cmd.LYRDSearchFiles },
			{ "b", cmd.LYRDSearchBuffers },
			{ "g", cmd.LYRDSearchGitFiles },
			{ "h", cmd.LYRDSearchRecentFiles },
			{ "l", cmd.LYRDSearchBufferLines },
			{ "c", cmd.LYRDSearchCommandHistory },
			{ "m", cmd.LYRDSearchKeyMappings },
			{ "g", cmd.LYRDSearchBufferTags },
			{ "t", cmd.LYRDTerminalList },
			{ "/", cmd.LYRDSearchLiveGrep },
			{ "f", cmd.LYRDSearchFiletypes },
			{ "o", cmd.LYRDSearchColorSchemes },
			{ "q", cmd.LYRDSearchQuickFixes },
			{ "H", cmd.LYRDSearchHighlights },
			{ ",", cmd.LYRDSearchCommands },
			{ "s", cmd.LYRDSearchCurrentString },
			{ "p", cmd.LYRDSearchRegisters },
			{ "R", cmd.LYRDReplaceInFiles },
			{ "r", cmd.LYRDReplace },
		}, icons.search.default),
		menu_header("g", "Git", {
			menu_header("f", "Gitflow", {
				{ "i", cmd.LYRDGitFlowInit },
				{ "f", cmd.LYRDGitFlowFeatureStart },
				{ "F", cmd.LYRDGitFlowFeatureFinish },
				{ "r", cmd.LYRDGitFlowReleaseStart },
				{ "R", cmd.LYRDGitFlowReleaseFinish },
				{ "h", cmd.LYRDGitFlowHotfixStart },
				{ "H", cmd.LYRDGitFlowHotfixFinish },
				{ "D", cmd.LYRDGitCheckoutDev },
				{ "M", cmd.LYRDGitCheckoutMain },
			}),
			menu_header("w", "Worktrees", {
				{ "t", cmd.LYRDGitWorkTreeList },
				{ "n", cmd.LYRDGitWorkTreeCreate },
				{ "e", cmd.LYRDGitWorkTreeCreateExistingBranch },
			}),
			{ "g", cmd.LYRDGitUI },
			{ "s", cmd.LYRDGitStatus },
			{ "c", cmd.LYRDGitCommit },
			{ "p", cmd.LYRDGitPush },
			{ "P", cmd.LYRDGitPull },
			{ "d", cmd.LYRDGitViewDiff },
			{ "a", cmd.LYRDGitStageAll },
			{ "b", cmd.LYRDGitViewBlame },
			{ "l", cmd.LYRDGitViewCurrentFileLog },
			{ "x", cmd.LYRDGitBrowseOnWeb },
		}, icons.git.default),
		menu_header("t", "Test", {
			{ "t", cmd.LYRDTest },
			{ "s", cmd.LYRDTestSuite },
			{ "b", cmd.LYRDTestFile },
			{ "F", cmd.LYRDTestDebugFunc },
			{ "f", cmd.LYRDTestFunc },
			{ "h", cmd.LYRDTestLast },
			{ "c", cmd.LYRDTestCoverage },
			{ "s", cmd.LYRDTestCoverageSummary },
			{ "v", cmd.LYRDTestSummary },
		}, icons.code.test),
		menu_header("p", "Packages", {
			{ "t", cmd.LYRDToolManager },
			{ "p", cmd.LYRDPluginManager },
			{ "i", cmd.LYRDPluginsInstall },
			{ "u", cmd.LYRDPluginsUpdate },
			{ "c", cmd.LYRDPluginsClean },
		}, icons.other.briefcase),
		menu_header("q", "Quit", {
			{ ".", cmd.LYRDWindowClose },
			{ "q", cmd.LYRDWindowForceCloseAll },
			{ "Q", cmd.LYRDWindowForceCloseAll },
		}, icons.action.exit),
		menu_header("r", "Run", {
			menu_header("h", "Http request", {
				{ "f", cmd.LYRDHttpEnvironmentFileSelect },
				{ "e", cmd.LYRDHttpEnvironmentSelect },
				{ "s", cmd.LYRDHttpSendRequest },
				{ "a", cmd.LYRDHttpSendAllRequests },
			}, icons.http.default),
			menu_header("r", "REPL", {
				{ "v", cmd.LYRDReplView },
				{ "r", cmd.LYRDReplRestart },
			}, icons.other.command),
		}, icons.code.run),
		menu_header("s", "Services", {
			{ "f", cmd.LYRDViewFileExplorer },
			{ "d", cmd.LYRDDatabaseUI },
			{ "c", cmd.LYRDContainersUI },
			{ "g", cmd.LYRDGitUI },
			{ "k", cmd.LYRDKubernetesUI },
			{ "t", cmd.LYRDTerminal },
			{ "T", cmd.LYRDTerminalList },
		}, icons.other.tools),
		menu_header("u", "User interface", {
			{ "w", cmd.LYRDBufferToggleWrap },
			{ "T", cmd.LYRDApplyCurrentTheme },
			{ "t", cmd.LYRDApplyNextTheme },
		}, icons.other.palette),
		menu_header("v", "View", {
			{ ".", cmd.LYRDViewHomePage },
			{ "D", cmd.LYRDLSPShowWorkspaceDiagnosticLocList },
			{ "c", cmd.LYRDLSPToggleLens },
			{ "d", cmd.LYRDLSPShowDocumentDiagnosticLocList },
			{ "e", cmd.LYRDViewFileExplorer },
			{ "f", cmd.LYRDViewFocusMode },
			{ "l", cmd.LYRDViewLocationList },
			{ "o", cmd.LYRDViewCodeOutline },
			{ "p", cmd.LYRDViewTreeSitterPlayground },
			{ "q", cmd.LYRDViewQuickFixList },
			{ "r", cmd.LYRDViewRegisters },
			{ "t", cmd.LYRDViewFileTree },
			{ "y", cmd.LYRDViewYankList },
		}, icons.action.view),
		{ "/", cmd.LYRDSearchBuffers },
	})
end

return L
