local mappings = require("LYRD.layers.mappings")
local commands = require("LYRD.layers.commands")
local c = commands.command_shortcut
local cmd = require("LYRD.layers.lyrd-commands").cmd

local L = { name = "LYRD Keyboard" }

function L.keybindings(s)
	mappings.keys(s, {
		{ "n", "<C-j>", cmd.LYRDPaneNavigateDown },
		{ "n", "<C-k>", cmd.LYRDPaneNavigateUp },
		{ "n", "<C-h>", cmd.LYRDPaneNavigateLeft },
		{ "n", "<C-l>", cmd.LYRDPaneNavigateRight },
		{ "n", "q", "<nop>" },
		{ "n", "s", "<nop>" },
		{ "n", "<F2>", cmd.LYRDViewFileTree },
		{ "n", "<F5>", cmd.LYRDDebugContinue },
		{ "n", "<F9>", cmd.LYRDDebugBreakpoint },
		{ "n", "<F10>", cmd.LYRDDebugStepOver },
		{ "n", "<F11>", cmd.LYRDDebugStepInto },
		{ "n", "<F2>", cmd.LYRDViewFileTree },
		{ "n", "<S-F2>", cmd.LYRDViewFileExplorer },
		{ "n", "<F3>", cmd.LYRDTestSummary },
		{ "n", "<C-s>", cmd.LYRDBufferSave },
		{ "i", "<C-s>", "<Esc>" .. c(cmd.LYRDBufferSave.name) },
		{ "n", "<C-p>", cmd.LYRDSearchFiles },
		{ "n", "<C-t>", cmd.LYRDSearchLiveGrep },
		{ "n", "<C-f>", cmd.LYRDResumeLastSearch },
		{ "n", "<A-Left>", cmd.LYRDBufferPrev },
		{ "n", "<A-Right>", cmd.LYRDBufferNext },
		{ "n", "<C-F4>", cmd.LYRDBufferClose },
		{ "n", "K", cmd.LYRDLSPHoverInfo },
		{ "n", "<C-S-k>", cmd.LYRDLSPSignatureHelp },
		{ "n", "gd", cmd.LYRDLSPFindDefinitions },
		{ "n", "gD", cmd.LYRDLSPFindDeclaration },
		{ "n", "gt", cmd.LYRDLSPFindTypeDefinition },
		{ "n", "gi", cmd.LYRDLSPFindImplementations },
		{ "n", "gr", cmd.LYRDLSPFindReferences },
		{ "n", "ga", cmd.LYRDLSPFindCodeActions },
		{ "n", "gA", cmd.LYRDLSPFindRangeCodeActions },
		{ "n", "gO", c([[call append(line('.')-1, '')]]) },
		{ "n", "go", c([[call append(line('.'), '')]]) },
		{ "n", [[gpi"]], [[vi""0p]] },
		{ "n", [[gpi']], [[vi'"0p]] },
		{ "n", "<A-PageUp>", cmd.LYRDLSPGotoPrevDiagnostic },
		{ "n", "<A-PageDown>", cmd.LYRDLSPGotoNextDiagnostic },
		{ "n", "<A-Enter>", cmd.LYRDLSPFindCodeActions },
		{ "n", "<C-r><C-r>", cmd.LYRDLSPRename },
		{ "n", "<C-r><C-f>", cmd.LYRDCodeRefactor },
		{ "v", "<C-r><C-f>", cmd.LYRDCodeRefactor },
	})

	mappings.leader_menu(s, {
		{ { "s" }, "Scratches" },
	})
	mappings.leader(s, {
		{ "n", { "<Space>" }, c("noh"), "Clear search highlights" },
		{ "n", { "." }, cmd.LYRDViewHomePage },
		{ "n", { "b" }, cmd.LYRDBreakLine },
		{ "n", { "c" }, cmd.LYRDBufferClose },
		{ "n", { "C" }, cmd.LYRDBufferCloseAll },
		{ "n", { "h" }, cmd.LYRDBufferSplitH },
		{ "n", { "v" }, cmd.LYRDBufferSplitV },
		{ "n", { "z" }, cmd.LYRDBufferPrev },
		{ "n", { "x" }, cmd.LYRDBufferNext },
		{ "n", { "a" }, cmd.LYRDLSPFindCodeActions },
		{ "n", { "A" }, cmd.LYRDLSPFindRangeCodeActions },
		{ "n", { "f" }, cmd.LYRDBufferFormat },
		{ "n", { "d" }, cmd.LYRDDebugToggleUI },
		{ "n", { "j" }, cmd.LYRDSmartCoder },
		{ "n", { "l" }, cmd.LYRDDiagnosticLinesToggle },
		{ "n", { "s", "n" }, cmd.LYRDScratchNew },
		{ "n", { "s", "s" }, cmd.LYRDScratchOpen },
		{ "n", { "s", "f" }, cmd.LYRDScratchSearch },
		{ "n", { "r", "n" }, cmd.LYRDLSPRename },
		{ "n", { "r", "f" }, cmd.LYRDCodeRefactor },
		{ "v", { "r", "f" }, cmd.LYRDCodeRefactor },
	})
	mappings.space_menu(s, {
		{ { "g" }, "Git Repository" },
		{ { "g", "f" }, "Gitflow" },
		{ { "a" }, "Artificial Intelligence" },
		{ { "b" }, "Buffers" },
		{ { "c" }, "Code" },
		{ { "c", "g" }, "Code Generation" },
		{ { "t" }, "Test" },
		{ { "f" }, "Services" },
		{ { "D" }, "Debug" },
		{ { "p" }, "Packages" },
		{ { "q" }, "Quit" },
		{ { "s" }, "Search" },
		{ { "u" }, "User interface" },
		{ { "v" }, "View" },
	})
	mappings.space(s, {
		{ "n", { "<Tab>" }, cmd.LYRDBufferJumpToLast },
		{ "n", { "/" }, cmd.LYRDSearchBuffers },
		{ "n", { "," }, cmd.LYRDBufferPrev },
		{ "n", { "." }, cmd.LYRDBufferNext },
		-- Artificial Intelligence Menu
		{ "n", { "a", "a" }, cmd.LYRDAIAssistant },
		{ "n", { "a", "r" }, cmd.LYRDAIRefactor },
		{ "n", { "a", "s" }, cmd.LYRDAISuggestions },
		-- View Menu
		{ "n", { "v", "." }, cmd.LYRDViewHomePage },
		{ "n", { "v", "t" }, cmd.LYRDViewFileTree },
		{ "n", { "v", "e" }, cmd.LYRDViewFileExplorer },
		{ "n", { "v", "l" }, cmd.LYRDViewLocationList },
		{ "n", { "v", "r" }, cmd.LYRDViewRegisters },
		{ "n", { "v", "y" }, cmd.LYRDViewYankList },
		{ "n", { "v", "q" }, cmd.LYRDViewQuickFixList },
		{ "n", { "v", "d" }, cmd.LYRDLSPShowDocumentDiagnosticLocList },
		{ "n", { "v", "D" }, cmd.LYRDLSPShowWorkspaceDiagnosticLocList },
		-- Buffer Menu
		{ "n", { "b", "e" }, cmd.LYRDBufferNew },
		{ "n", { "b", "n" }, cmd.LYRDBufferNext },
		{ "n", { "b", "p" }, cmd.LYRDBufferPrev },
		{ "n", { "b", "d" }, cmd.LYRDBufferClose },
		{ "n", { "b", "D" }, cmd.LYRDBufferForceClose },
		{ "n", { "b", "f" }, cmd.LYRDBufferFormat },
		{ "n", { "b", "x" }, cmd.LYRDBufferCloseAll },
		{ "n", { "b", "X" }, cmd.LYRDBufferForceCloseAll },
		{ "n", { "b", "h" }, cmd.LYRDBufferSplitH },
		{ "n", { "b", "v" }, cmd.LYRDBufferSplitV },
		{ "n", { "b", "w" }, cmd.LYRDBufferSetReadOnly },
		{ "n", { "b", "Y" }, cmd.LYRDBufferCopy },
		{ "n", { "b", "P" }, cmd.LYRDBufferPaste },
		{ "n", { "b", "/" }, cmd.LYRDSearchBuffers },
		{ "n", { "b", "s" }, cmd.LYRDBufferSave },
		{ "n", { "b", "S" }, cmd.LYRDBufferSaveAll },
		-- Packages
		{ "n", { "p", "i" }, cmd.LYRDPluginsInstall },
		{ "n", { "p", "u" }, cmd.LYRDPluginsUpdate },
		{ "n", { "p", "c" }, cmd.LYRDPluginsClean },
		{ "n", { "p", "t" }, cmd.LYRDTerminal },
		-- Quit Menu
		{ "n", { "q", "." }, cmd.LYRDWindowClose },
		{ "n", { "q", "q" }, cmd.LYRDWindowForceCloseAll },
		{ "n", { "q", "Q" }, cmd.LYRDWindowForceCloseAll },
		-- UI Menu
		{ "n", { "u", "w" }, cmd.LYRDBufferToggleWrap },
		-- Services
		{ "n", { "f", "f" }, cmd.LYRDViewFileExplorer },
		{ "n", { "f", "d" }, cmd.LYRDDatabaseUI },
		{ "n", { "f", "c" }, cmd.LYRDContainersUI },
		{ "n", { "f", "g" }, cmd.LYRDGitUI },
		{ "n", { "f", "k" }, cmd.LYRDKubernetesUI },
		-- Search Menu
		{ "n", { "s", "." }, cmd.LYRDSearchFiles },
		{ "n", { "s", "b" }, cmd.LYRDSearchBuffers },
		{ "n", { "s", "g" }, cmd.LYRDSearchGitFiles },
		{ "n", { "s", "h" }, cmd.LYRDSearchRecentFiles },
		{ "n", { "s", "l" }, cmd.LYRDSearchBufferLines },
		{ "n", { "s", "c" }, cmd.LYRDSearchCommandHistory },
		{ "n", { "s", "m" }, cmd.LYRDSearchKeyMappings },
		{ "n", { "s", "t" }, cmd.LYRDSearchBufferTags },
		{ "n", { "s", "/" }, cmd.LYRDSearchLiveGrep },
		{ "n", { "s", "f" }, cmd.LYRDSearchFiletypes },
		{ "n", { "s", "o" }, cmd.LYRDSearchColorSchemes },
		{ "n", { "s", "q" }, cmd.LYRDSearchQuickFixes },
		{ "n", { "s", "H" }, cmd.LYRDSearchHighlights },
		{ "n", { "s", "," }, cmd.LYRDSearchCommands },
		{ "n", { "s", "s" }, cmd.LYRDSearchCurrentString },
		{ "n", { "s", "p" }, cmd.LYRDSearchRegisters },
		-- Git Menu
		{ "n", { "g", "g" }, cmd.LYRDGitUI },
		{ "n", { "g", "s" }, cmd.LYRDGitStatus },
		{ "n", { "g", "c" }, cmd.LYRDGitCommit },
		{ "n", { "g", "p" }, cmd.LYRDGitPush },
		{ "n", { "g", "P" }, cmd.LYRDGitPull },
		{ "n", { "g", "d" }, cmd.LYRDGitViewDiff },
		{ "n", { "g", "a" }, cmd.LYRDGitStageAll },
		{ "n", { "g", "b" }, cmd.LYRDGitViewBlame },
		{ "n", { "g", "l" }, cmd.LYRDGitViewCurrentFileLog },
		{ "n", { "g", "w" }, cmd.LYRDGitBrowseOnWeb },
		{ "n", { "g", "f", "i" }, cmd.LYRDGitFlowInit },
		{ "n", { "g", "f", "f" }, cmd.LYRDGitFlowFeatureStart },
		{ "n", { "g", "f", "F" }, cmd.LYRDGitFlowFeatureFinish },
		{ "n", { "g", "f", "r" }, cmd.LYRDGitFlowReleaseStart },
		{ "n", { "g", "f", "R" }, cmd.LYRDGitFlowReleaseFinish },
		{ "n", { "g", "f", "h" }, cmd.LYRDGitFlowHotfixStart },
		{ "n", { "g", "f", "H" }, cmd.LYRDGitFlowHotfixFinish },
		{ "n", { "g", "f", "D" }, cmd.LYRDGitCheckoutDev },
		{ "n", { "g", "f", "M" }, cmd.LYRDGitCheckoutMain },
		-- Code Menu
		{ "n", { "c", "a" }, cmd.LYRDLSPFindCodeActions },
		{ "n", { "c", "A" }, cmd.LYRDLSPFindRangeCodeActions },
		{ "n", { "c", "b" }, cmd.LYRDCodeBuild },
		{ "n", { "c", "r" }, cmd.LYRDCodeRun },
		{ "n", { "c", "R" }, cmd.LYRDCodeRefactor },
		{ "n", { "c", "t" }, cmd.LYRDCodeAlternateFile },
		{ "n", { "c", "l" }, cmd.LYRDDiagnosticLinesToggle },
		{ "n", { "c", "i" }, cmd.LYRDCodeFixImports },
		{ "n", { "c", "c" }, cmd.LYRDCodeGlobalCheck },
		{ "n", { "c", "I" }, cmd.LYRDCodeImplementInterface },
		{ "n", { "c", "s" }, cmd.LYRDCodeFillStructure },
		{ "n", { "c", "S" }, cmd.LYRDCodeInsertSnippet },
		{ "n", { "c", "g", "x" }, cmd.LYRDCodeGenerate },
		{ "n", { "c", "g", "g" }, cmd.LYRDCodeProduceGetter },
		{ "n", { "c", "g", "s" }, cmd.LYRDCodeProduceSetter },
		{ "n", { "c", "g", "m" }, cmd.LYRDCodeProduceMapping },
		-- Test menu
		{ "n", { "t", "t" }, cmd.LYRDTest },
		{ "n", { "t", "s" }, cmd.LYRDTestSuite },
		{ "n", { "t", "F" }, cmd.LYRDTestFile },
		{ "n", { "t", "f" }, cmd.LYRDTestFunc },
		{ "n", { "t", "l" }, cmd.LYRDTestLast },
		{ "n", { "t", "c" }, cmd.LYRDTestCoverage },
		{ "n", { "t", "v" }, cmd.LYRDTestSummary },

		-- Debug Menu
		{ "n", { "D", "c" }, cmd.LYRDDebugContinue },
		{ "n", { "D", "i" }, cmd.LYRDDebugStepInto },
		{ "n", { "D", "o" }, cmd.LYRDDebugStepOver },
		{ "n", { "D", "s" }, cmd.LYRDDebugStop },
		{ "n", { "D", "b" }, cmd.LYRDDebugBreakpoint },
		{ "n", { "D", "u" }, cmd.LYRDDebugToggleUI },
		{ "n", { "D", "r" }, cmd.LYRDDebugToggleRepl },
	})
end

return L
