local commands = require("LYRD.layers.commands")
local Command = commands.Command
local icons = require("LYRD.layers.icons")

local function commandPalette()
	local items = commands.get_command_list()

	vim.ui.select(items, {
		prompt = "Select a command to execute",
		format_item = function(item)
			return item.label
		end,
	}, function(item)
		if item and item.cmd then
			item.cmd:execute()
		end
	end)
end

---@class LYRD.layer.LYRDCommands: LYRD.shared.setup.Module
local L = {
	name = "LYRD Commands",
	vscode_compatible = true,
	unskippable = true,
	cmd = {
		LYRDAIAssistant = Command:new("AI: Assistant", nil, icons.ai.assistant, true),
		LYRDAICli = Command:new("AI: Cli tool", nil, icons.ai.cli, true),
		LYRDAICliPrompt = Command:new("AI: Send a prompt to AI Cli tools", nil, icons.ai.prompt, true),
		LYRDAICliSelect = Command:new("AI: Select Cli tools", nil, icons.ai.select, true),
		LYRDAIAsk = Command:new("AI: Ask", nil, icons.ai.prompt, true),
		LYRDAIEdit = Command:new("AI: Edit", nil, icons.ai.edit, true),
		LYRDAIGenerateDocumentation = Command:new("AI: Document current element", nil, icons.ai.document, true),
		LYRDBreakLine = Command:new(
			"Break current line",
			":s/[,(]/&\r/ge|:noh|:'[,']normal==",
			icons.action.break_line
		),
		LYRDBufferClose = Command:new("Buffer: Close", ":bd", icons.action.close),
		LYRDBufferClearContent = Command:new("Buffer: Clear content", ":%d _", icons.action.clean),
		LYRDBufferCloseAll = Command:new("Buffer: Close all", ":bufdo bd", icons.action.close_many),
		LYRDBufferCopy = Command:new("Buffer: Copy content to clipboard", ':normal! ggVG"+y``', icons.action.copy),
		LYRDBufferForceClose = Command:new("Buffer: Force close", ":bd!", icons.action.kill),
		LYRDBufferForceCloseAll = Command:new("Buffer: Force close all", ":bufdo bd!", icons.action.kill_target),
		LYRDBufferFormat = Command:new("Format document", nil, icons.action.format, true),
		LYRDBufferJumpToLast = Command:new("Buffer: Jump to last", ":b#", icons.arrow.up_left),
		LYRDBufferNew = Command:new("Buffer: New", ":enew", icons.file.new),
		LYRDBufferNext = Command:new("Buffer: Next", ":bn", icons.chevron.double_right, false, true),
		LYRDBufferPaste = Command:new("Buffer: Replace with clipboard content", ':normal! ggdG"+P', icons.action.paste),
		LYRDBufferPrev = Command:new("Buffer: Previous", ":bp", icons.chevron.double_left, false, true),
		LYRDBufferSave = Command:new("Buffer: Save current file", ":w", icons.action.save, false, true),
		LYRDBufferSaveAll = Command:new("Buffer: Save all files", ":wall", icons.action.save_all),
		LYRDBufferSetReadOnly = Command:new("Buffer: Toggle read only mode", ":setl readonly!", icons.action.toggle_on),
		LYRDBufferSplitH = Command:new("Buffer: Horizonal split", ":split", icons.action.split_h),
		LYRDBufferSplitV = Command:new("Buffer: Vertical split", ":vsplit", icons.action.split_v),
		LYRDBufferToggleWrap = Command:new("Buffer: Toggle line wrap", ":setlocal wrap!", icons.action.wrap),
		LYRDBufferReload = Command:new("Buffer: Reload from disk", ":e", icons.action.reload),
		LYRDCodeAlternateFile = Command:new("Code: Toggle alternate file", nil, icons.file.swap),
		LYRDCodeBuild = Command:new("Code: Build", nil, icons.code.build),
		LYRDCodeBuildAll = Command:new("Code: Build all", nil, icons.code.build),
		LYRDCodeFillStructure = Command:new("Code: Fill structure", nil, icons.code.outline),
		LYRDCodeFixImports = Command:new("Code: Fix imports", nil, icons.code.fix),
		LYRDCodeGenerate = Command:new("Code: Run Generator Tool", nil, icons.code.generate),
		LYRDCodeGlobalCheck = Command:new("Code: Global check", nil, icons.code.check),
		LYRDCodeImplementInterface = Command:new("Code: Implement interface", nil, icons.code.interface),
		LYRDCodeInsertSnippet = Command:new("Code Snippet: Insert at cursor", nil, icons.code.snippet),
		LYRDCodeCreateSnippet = Command:new("Code Snippet: Create new", nil, icons.code.snippet, true),
		LYRDCodeEditSnippet = Command:new("Code Snippet: Edit", nil, icons.code.snippet),
		LYRDCodeProduceGetter = Command:new("Code: Generate getters code", nil, icons.code.generate),
		LYRDCodeProduceMapping = Command:new("Code: Generate mappings code", nil, icons.code.generate),
		LYRDCodeProduceSetter = Command:new("Code: Generate setters code", nil, icons.code.generate),
		LYRDCodeRestorePackages = Command:new("Project: Restore packages", nil, icons.code.package),
		LYRDCodeTooling = Command:new("Code: Language tooling", nil, icons.other.tools),
		LYRDCodeRefactor = Command:new("Code: Refactor", nil, icons.code.refactor),
		LYRDCodeRunSelection = Command:new("Code: Run selection", nil, icons.code.run, true),
		LYRDCodeRun = Command:new("Code: Run file", nil, icons.code.run),
		LYRDCodeQuerySelection = Command:new("Code: Run selection as query", nil, icons.code.run, true),
		LYRDCodeQuerySelectionAsEditable = Command:new(
			"Code: Run selection as query with editable results",
			nil,
			icons.code.run,
			true
		),
		LYRDCodeSelectEnvironment = Command:new("Code: Select environment", nil, icons.other.environment),
		LYRDCodeSecrets = Command:new("Project: Edit Secrets", nil, icons.other.secret),
		LYRDCodeLanguageVersion = Command:new("Code: Select language version/dialect", nil, icons.action.switch),
		LYRDCodeOrganizeFile = Command:new("Code: Organize file", nil, icons.code.fix),
		LYRDDebugBreakpoint = Command:new("Debug: Toggle breakpoint", nil, icons.debug.breakpoint),
		LYRDDebugStart = Command:new("Debug: Start session", nil, icons.debug.play),
		LYRDDebugContinue = Command:new("Debug: Continue", nil, icons.debug.play),
		LYRDDebugStepInto = Command:new("Debug: Step into", nil, icons.debug.step_into),
		LYRDDebugStepOut = Command:new("Debug: Step out", nil, icons.debug.step_out),
		LYRDDebugStepOver = Command:new("Debug: Step over", nil, icons.debug.step_over),
		LYRDDebugStop = Command:new("Debug: Stop", nil, icons.debug.terminate),
		LYRDDebugToggleRepl = Command:new("Debug: Toggle Repl", nil, icons.action.toggle_on),
		LYRDDebugToggleUI = Command:new("Debug: Show UI", nil, icons.debug.breakpoint),
		LYRDDevServerStart = Command:new("Live server: Start", nil, icons.apps.server),
		LYRDDevExposeLocalServer = Command:new("Expose local port to the web", nil, icons.apps.exposed_server),
		LYRDScanForSecrets = Command:new("Diagnostic: Scan for secrets in current workspace", nil, icons.other.secret),
		LYRDDiagnosticLinesToggle = Command:new("Diagnostic: Toggle virtual lines", nil, icons.action.toggle_on),
		LYRDEditTextCase = Command:new("Change text case", nil, icons.other.text_case),
		LYRDGitUI = Command:new("Git UI", nil, icons.apps.git),
		LYRDGrammarToggle = Command:new("Toggle grammar checker", nil, icons.action.toggle_on),
		LYRDGitBrowseOnWeb = Command:new("Git: Browse line on web", nil, icons.apps.browser),
		LYRDGitCheckoutDev = Command:new("Git: Checkout Develop branch", nil, icons.git.branch),
		LYRDGitCheckoutMain = Command:new("Git: Checkout Main branch", nil, icons.git.branch),
		LYRDGitCommit = Command:new("Git: Commit changes", nil, icons.git.commit),
		LYRDGitMergeConflicts = Command:new("Git: View Merge Conflicts", nil, icons.git.conflict),
		LYRDGitFlowFeatureFinish = Command:new("Gitflow: Feature finish", nil, icons.git.commit_end),
		LYRDGitFlowFeatureStart = Command:new("Gitflow: Feature start", nil, icons.git.commit_start),
		LYRDGitFlowFeaturePublish = Command:new("Gitflow: Feature publish (pull req.)", nil, icons.git.pull_request),
		LYRDGitFlowHotfixFinish = Command:new("Gitflow: Hotfix finish", nil, icons.git.commit_end),
		LYRDGitFlowHotfixStart = Command:new("Gitflow: Hotfix start", nil, icons.git.commit_start),
		LYRDGitFlowHotfixPublish = Command:new("Gitflow: Hotfix publish (pull req.)", nil, icons.git.pull_request),
		LYRDGitFlowInit = Command:new("Gitflow: Init", nil, icons.git.init),
		LYRDGitFlowReleaseFinish = Command:new("Gitflow: Release finish", nil, icons.git.commit_end),
		LYRDGitFlowReleaseStart = Command:new("Gitflow: Release start", nil, icons.git.commit_start),
		LYRDGitFlowReleasePublish = Command:new("Gitflow: Release publish (pull req.)", nil, icons.git.pull_request),
		LYRDGitPull = Command:new("Git: Pull", nil, icons.git.pull),
		LYRDGitPush = Command:new("Git: Push", nil, icons.git.push),
		LYRDGitStageAll = Command:new("Git: Stage all", nil, icons.git.stage_all),
		LYRDGitStatus = Command:new("Git: Status", nil, icons.git.status),
		LYRDGitViewBlame = Command:new("Git: View blame", nil, icons.git.blame),
		LYRDGitViewCurrentFileLog = Command:new("Git: Current file log", nil, icons.git.log),
		LYRDGitViewDiff = Command:new("Git: View diff", nil, icons.git.diff),
		LYRDGitViewLog = Command:new("Git: File log", nil, icons.git.log),
		LYRDGitCompareWithBranch = Command:new("Git: Compare file with another branch", nil, icons.git.diff),
		LYRDGithubIssueList = Command:new("Github: List issues", nil, icons.git.issue.list),
		LYRDGithubIssueClose = Command:new("GitHub: Close issue", nil, icons.git.issue.closed),
		LYRDGithubIssueReopen = Command:new("GitHub: Reopen issue", nil, icons.git.issue.reopened),
		LYRDGithubIssueCreate = Command:new("GitHub: Create issue", nil, icons.git.issue.open),
		LYRDGithubIssueDevelop = Command:new("GitHub: Develop issue", nil, icons.git.issue.develop_branch),
		LYRDGithubPullRequestList = Command:new("GitHub: List pull requests", nil, icons.git.pr.list),
		LYRDGithubPullRequestCreate = Command:new("GitHub: Create pull request", nil, icons.git.pr.open),
		LYRDGithubPullRequestClose = Command:new("GitHub: Close pull request", nil, icons.git.pr.closed),
		LYRDGitWorkTreeCreate = Command:new("Git: Create Worktree", nil, icons.folder.new),
		LYRDGitWorkTreeCreateExistingBranch = Command:new(
			"Git: Create Worktree for existing branch",
			nil,
			icons.folder.new
		),
		LYRDGitWorkTreeList = Command:new("Git: List Worktrees", nil, icons.git.worktree),
		LYRDGitViewGraph = Command:new("Git: View Repository Graph", nil, icons.git.branch),
		LYRDLSPToggleLens = Command:new("Toggle Code Lens", nil, icons.action.toggle_on),
		LYRDLSPFindCodeActions = Command:new("View Code Actions", nil, icons.action.code_action),
		LYRDLSPFindDeclaration = Command:new("Go to Declaration", nil, icons.code.navigate),
		LYRDLSPFindDefinitions = Command:new("Go to Definition", nil, icons.code.navigate),
		LYRDLSPFindDocumentDiagnostics = Command:new("Find Document Diagnostics", nil, icons.diagnostic.search),
		LYRDLSPFindDocumentSymbols = Command:new("Find Document Symbols", nil, icons.code.symbol),
		LYRDLSPFindImplementations = Command:new("Find Implementations", nil, icons.code.navigate),
		LYRDLSPFindLineDiagnostics = Command:new("Find Line Diagnostics", nil, icons.diagnostic.search),
		LYRDLSPFindRangeCodeActions = Command:new("View Range Actions", nil, icons.action.code_action),
		LYRDLSPFindReferences = Command:new("Find References", nil, icons.code.navigate),
		LYRDLSPFindTypeDefinition = Command:new("Go to Type Definition", nil, icons.code.navigate),
		LYRDLSPFindWorkspaceDiagnostics = Command:new("Find Workspace Diagnostics", nil, icons.diagnostic.search),
		LYRDLSPFindWorkspaceSymbols = Command:new("Find Workspace Symbols", nil, icons.code.symbol),
		LYRDLSPGotoNextDiagnostic = Command:new("Diagnostic: Goto Next", nil, icons.diagnostic.next),
		LYRDLSPGotoPrevDiagnostic = Command:new("Diagnostic: Goto Previous", nil, icons.diagnostic.prev),
		LYRDLSPHoverInfo = Command:new("Show hover information", nil, icons.code.hint),
		LYRDLSPRename = Command:new("Refactor: Rename symbol", nil, icons.code.rename),
		LYRDLSPShowDocumentDiagnosticLocList = Command:new("View Document diagnostics", nil, icons.diagnostic.search),
		LYRDLSPShowWorkspaceDiagnosticLocList = Command:new("View Workspace diagnostics", nil, icons.diagnostic.search),
		LYRDLSPSignatureHelp = Command:new("View Signature help", nil, icons.code.hint),
		LYRDToolManager = Command:new("Config: Tool Manager", nil, icons.other.tools),
		LYRDPluginManager = Command:new("Config: Plugin Manager", ":Lazy", icons.other.plug),
		LYRDPluginsClean = Command:new("Config: Clean plugins", ":Lazy clean", icons.action.clean),
		LYRDPluginsInstall = Command:new("Config: Install plugins", ":Lazy install", icons.action.install),
		LYRDPluginsUpdate = Command:new("Config: Update plugins", ":Lazy sync", icons.action.update),
		LYRDSearchBufferLines = Command:new("Search: Lines", nil, icons.search.lines),
		LYRDSearchBufferTags = Command:new("Search: Tags", nil, icons.search.tags),
		LYRDSearchBuffers = Command:new("Search: buffers", nil, icons.search.buffers),
		LYRDSearchColorSchemes = Command:new("Search: Color Schemes", nil, icons.search.default),
		LYRDSearchCommandHistory = Command:new("Search: Recent comands", nil, icons.search.history),
		LYRDSearchCommands = Command:new("Search: Commands", nil, icons.search.commands),
		LYRDSearchCurrentString = Command:new("Search: Current string in files", nil, icons.search.default),
		LYRDSearchAllFiles = Command:new("Search: All files", nil, icons.search.files),
		LYRDSearchFiles = Command:new("Search: Files", nil, icons.search.files),
		LYRDSearchFiletypes = Command:new("Search: Filetypes", nil, icons.search.default),
		LYRDSearchGitFiles = Command:new("Search Git files", nil, icons.search.files),
		LYRDSearchHighlights = Command:new("Search: Highlights", nil, icons.search.default),
		LYRDSearchKeyMappings = Command:new("Search: Key Maps", nil, icons.search.keys),
		LYRDSearchLiveGrep = Command:new("Search: Text in files (Live Grep)", nil, icons.search.default),
		LYRDSearchQuickFixes = Command:new("Search: Quick Fixes", nil, icons.diagnostic.search),
		LYRDSearchRecentFiles = Command:new("Search: Recent files", nil, icons.search.history),
		LYRDSearchRegisters = Command:new("Search: Registers", nil, icons.search.default),
		LYRDSearchSymbols = Command:new("Search: Symbols", nil, icons.search.default),
		LYRDSearchSnippets = Command:new("Search: Snippets", nil, icons.code.snippet),
		LYRDSearchMacros = Command:new("Search: Macros", nil, icons.other.macro),
		LYRDResumeLastSearch = Command:new("Search: Resume last", nil, icons.search.history),
		LYRDSmartCoder = Command:new("Smart code generator", nil, icons.code.generate),
		LYRDTerminalList = Command:new("View terminal list", nil, icons.search.layers),
		LYRDTerminal = Command:new("Terminal", ":terminal", icons.apps.terminal),
		LYRDTest = Command:new("Test: Everything", nil, icons.code.test),
		LYRDTestCoverageSummary = Command:new("Test: View Coverage Summary", nil, icons.code.test),
		LYRDTestCoverage = Command:new("Test: Toggle Coverage", nil, icons.code.test),
		LYRDTestFile = Command:new("Test: Current file", nil, icons.code.test),
		LYRDTestDebugFunc = Command:new("Test: Debug current function", nil, icons.debug.breakpoint),
		LYRDTestFunc = Command:new("Test: current function", nil, icons.code.test),
		LYRDTestLast = Command:new("Test: Repeat last", nil, icons.action.repeat_once),
		LYRDTestSuite = Command:new("Test: Suite", nil, icons.code.test),
		LYRDTestSummary = Command:new("Test: View summary", nil, icons.code.test),
		LYRDTestOutput = Command:new("Test: View output", nil, icons.other.report),
		LYRDViewFileExplorer = Command:new("File Explorer", nil, icons.apps.file_explorer),
		LYRDViewFileExplorerAlt = Command:new("File Explorer (Alternative)", nil, icons.apps.file_explorer),
		LYRDViewFileTree = Command:new("File Tree", nil, icons.other.filetree),
		LYRDViewHomePage = Command:new("Home page", nil, icons.other.home),
		LYRDViewLocationList = Command:new("Location list"),
		LYRDViewQuickFixList = Command:new("QuickFix", ":cope"),
		LYRDViewLSPInfo = Command:new("View LSP info", ":checkhealth vim.lsp", icons.code.check),
		LYRDViewFocusMode = Command:new("Focus mode", nil, icons.other.focus),
		LYRDViewMarks = Command:new("Marks", nil, icons.other.bookmark),
		LYRDWindowClose = Command:new("Window: Close", ":q"),
		LYRDWindowCloseAll = Command:new("Window: Close all", ":qa"),
		LYRDWindowForceCloseAll = Command:new("Window: Force Quit", ":qa!"),
		LYRDPaneNavigateLeft = Command:new("Navigate to panel left", "<C-w>h", icons.arrow.left),
		LYRDPaneNavigateDown = Command:new("Navigate to panel below", "<C-w>j", icons.arrow.down),
		LYRDPaneNavigateUp = Command:new("Navigate to panel up", "<C-w>k", icons.arrow.up),
		LYRDPaneNavigateRight = Command:new("Navigate to panel right", "<C-w>l", icons.arrow.right),
		LYRDPaneResizeLeft = Command:new("Resize to panel left", nil, icons.arrow.collapse_left),
		LYRDPaneResizeDown = Command:new("Resize to panel below", nil, icons.arrow.collapse_down),
		LYRDPaneResizeUp = Command:new("Resize to panel up", nil, icons.arrow.collapse_up),
		LYRDPaneResizeRight = Command:new("Resize to panel right", nil, icons.arrow.collapse_right),
		LYRDPaneSwapLeft = Command:new("Swap to panel left", nil, icons.arrow.expand_left),
		LYRDPaneSwapDown = Command:new("Swap to panel below", nil, icons.arrow.expand_down),
		LYRDPaneSwapUp = Command:new("Swap to panel up", nil, icons.arrow.expand_up),
		LYRDPaneSwapRight = Command:new("Swap to panel right", nil, icons.arrow.expand_right),
		LYRDDatabaseUI = Command:new("Database UI", nil, icons.other.database),
		LYRDDatabaseOutput = Command:new("Database Output", nil, icons.other.database),
		LYRDContainersUI = Command:new("Running containers UI", nil, icons.other.docker),
		LYRDKubernetesUI = Command:new("Kubernetes UI", nil, icons.other.kubernetes),
		LYRDScratchNew = Command:new("Scratch: Create new", nil, icons.file.scratch),
		LYRDScratchDelete = Command:new("Scratch: Delete", nil, icons.action.delete),
		LYRDScratchOpen = Command:new("Scratch: Search file", nil, icons.search.files),
		LYRDScratchSearch = Command:new("Scratch: Search text", nil, icons.search.lines),
		LYRDReplace = Command:new("Search and replace in current file", nil, icons.action.replace_text),
		LYRDReplaceInFiles = Command:new("Search and replace in files", nil, icons.action.replace_in_files),
		LYRDWindowZoom = Command:new("Toggles zoom in the selected window", nil, icons.other.expand),
		LYRDApplyCurrentTheme = Command:new("Apply current theme", nil, icons.other.palette),
		LYRDApplyNextTheme = Command:new("Apply next favorite theme", nil, icons.other.palette),
		LYRDClearSearchHighlights = Command:new("Clear search highlights", ":noh", icons.other.highlighter),
		LYRDViewCodeOutline = Command:new("View code outline", nil, icons.code.outline),
		LYRDViewTreeSitterPlayground = Command:new("TreeSitter playground", nil, icons.code.parser),
		LYRDReplView = Command:new("View REPL", nil, icons.code.run),
		LYRDReplRestart = Command:new("REPL Restart", nil, icons.code.restart),
		LYRDReplNotebookRunCell = Command:new("Notebook: Run cell", nil, icons.code.run),
		LYRDReplNotebookRunCellAndMove = Command:new("Notebook: Run cell and move to the next.", nil, icons.code.run),
		LYRDReplNotebookRunAllCells = Command:new("Notebook: Run all cells", nil, icons.code.run),
		LYRDReplNotebookRunAllAbove = Command:new("Notebook: Run cells above", nil, icons.code.run),
		LYRDReplNotebookRunAllBelow = Command:new("Notebook: Run cells below", nil, icons.code.run),
		LYRDReplNotebookMoveCellUp = Command:new("Notebook: Move current cell up", nil, icons.arrow.up),
		LYRDReplNotebookMoveCellDown = Command:new("Notebook: Move current cell down", nil, icons.arrow.down),
		LYRDReplNotebookAddCellAbove = Command:new("Notebook: Add cell above", nil, icons.arrow.expand_up),
		LYRDReplNotebookAddCellBelow = Command:new("Notebook: dd cell below", nil, icons.arrow.expand_down),
		LYRDPasteImage = Command:new("Paste image", nil, icons.images.add),
		LYRDInsertImage = Command:new("Insert image", nil, icons.images.search),
		LYRDHardModeToggle = Command:new("Toggle hard mode", nil, icons.action.toggle_on),
		LYRDTasksToggle = Command:new("Tasks: Toggle view", nil, icons.other.eye),
		LYRDTasksRun = Command:new("Tasks: Select and run", nil, icons.action.run_task),
		LYRDTasksConfigure = Command:new("Tasks: Configure for workspace", nil, icons.other.task),
		LYRDTasksConfigureLaunch = Command:new("Tasks: Configure launch profile", nil, icons.other.launch),
		LYRDToggleBufferDecorations = Command:new("Toggle buffer decorations", nil, icons.action.toggle_on),
		LYRDEditLocalConfig = Command:new("Config: Edit local settings", nil, icons.other.wrench),
		LYRDBookmarkAddLocal = Command:new("Add local bookmark", nil, icons.other.bookmark),
		LYRDBookmarkAddGlobal = Command:new("Add global bookmark", nil, icons.other.bookmark),
		LYRDBookmarkSearch = Command:new("Show bookmarks", nil, icons.other.bookmark),
		LYRDBookmarkToggle = Command:new("Toggle bookmarks view", nil, icons.other.bookmark),
		LYRDBookmarkDelete = Command:new("Delete bookmark", nil, icons.action.delete),
		LYRDCopyRelativeFilePath = Command:new("Copy relative file path", nil, icons.file.symlink),
		LYRDCopyAbsoluteFilePath = Command:new("Copy absolute file path", nil, icons.file.symlink),
		LYRDCopyFileName = Command:new("Copy file name", nil, icons.file.symlink),
		LYRDCopyWorkingDirectory = Command:new("Copy working directory", nil, icons.folder.symlink),
		LYRDPasteFromHistory = Command:new("Paste from history", nil, icons.action.paste),
		LYRDInsertLineAbove = Command:new("Insert line above", ":call append(line('.')-1, '')", icons.arrow.up),
		LYRDInsertLineBelow = Command:new("Insert line below", ":call append(line('.'), '')", icons.arrow.down),
		LYRDDiffThis = Command:new("Diff: Add to comparisson", ":diffthis", icons.action.compare),
		LYRDDiffOff = Command:new("Diff: Turn comparisson off", ":diffoff", icons.action.compare),
		LYRDBindScroll = Command:new("Diff: Bind scroll on buffers", ":set scrollbind", icons.action.compare),
		LYRDCommandPalette = Command:new("Command Palette", commandPalette, icons.other.palette),
	},
}

function L.settings()
	commands.register(L.cmd)
end

return L
